"""add_telemetry_logs

Revision ID: 8e167af8a641
Revises: ea2a52ef6244
Create Date: 2026-03-05 18:35:14.154474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e167af8a641'
down_revision: Union[str, None] = 'ea2a52ef6244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=True),
    sa.Column('load_time_ms', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_event_ts', 'telemetry_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_telemetry_user_ts', 'telemetry_logs', ['user_email', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telemetry_user_ts', table_name='telemetry_logs')
    op.drop_index('idx_telemetry_event_ts', table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    # ### end Alembic commands ###
