"""initial_schema

Revision ID: ea2a52ef6244
Revises: 
Create Date: 2026-03-05 15:48:28.571434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2a52ef6244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_timestamp', 'audit_log', ['action', 'timestamp'], unique=False)
    op.create_index('idx_user_action', 'audit_log', ['user_email', 'action'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_email'), 'audit_log', ['user_email'], unique=False)
    op.create_table('entity_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_code', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=500), nullable=True),
    sa.Column('sales_employee', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('market_group', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('sub_region', sa.String(length=100), nullable=True),
    sa.Column('channel_level', sa.String(length=100), nullable=False),
    sa.Column('company_group', sa.String(length=100), nullable=True),
    sa.Column('sales_employee_cleaned', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_code_active', 'entity_mappings', ['customer_code', 'is_active'], unique=False)
    op.create_index('idx_customer_name_active', 'entity_mappings', ['customer_name', 'is_active'], unique=False)
    op.create_index('idx_sales_employee_active', 'entity_mappings', ['sales_employee', 'is_active'], unique=False)
    op.create_index(op.f('ix_entity_mappings_customer_code'), 'entity_mappings', ['customer_code'], unique=False)
    op.create_index(op.f('ix_entity_mappings_customer_name'), 'entity_mappings', ['customer_name'], unique=False)
    op.create_index(op.f('ix_entity_mappings_is_active'), 'entity_mappings', ['is_active'], unique=False)
    op.create_index(op.f('ix_entity_mappings_sales_employee'), 'entity_mappings', ['sales_employee'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=200), nullable=False),
    sa.Column('output_log', sa.Text(), nullable=True),
    sa.Column('csv_url', sa.String(length=500), nullable=True),
    sa.Column('xlsx_url', sa.String(length=500), nullable=True),
    sa.Column('zip_url', sa.String(length=500), nullable=True),
    sa.Column('core_market_csv_url', sa.String(length=500), nullable=True),
    sa.Column('usa_spa_csv_url', sa.String(length=500), nullable=True),
    sa.Column('unmapped_url', sa.String(length=500), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_created', 'report_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_report_runs_created_at'), 'report_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_runs_status'), 'report_runs', ['status'], unique=False)
    op.create_index(op.f('ix_report_runs_timestamp'), 'report_runs', ['timestamp'], unique=True)
    op.create_table('unmapped_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_name', sa.String(length=500), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_ar_value_keur', sa.Float(), nullable=False),
    sa.Column('sap_extract_files', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_to_mapping_id', sa.Integer(), nullable=True),
    sa.Column('run_timestamp', sa.String(length=20), nullable=False),
    sa.Column('source_file', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_to_mapping_id'], ['entity_mappings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_name_type', 'unmapped_logs', ['entity_name', 'entity_type'], unique=False)
    op.create_index('idx_entity_status', 'unmapped_logs', ['entity_type', 'status'], unique=False)
    op.create_index(op.f('ix_unmapped_logs_entity_name'), 'unmapped_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_unmapped_logs_entity_type'), 'unmapped_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_unmapped_logs_run_timestamp'), 'unmapped_logs', ['run_timestamp'], unique=False)
    op.create_index(op.f('ix_unmapped_logs_status'), 'unmapped_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unmapped_logs_status'), table_name='unmapped_logs')
    op.drop_index(op.f('ix_unmapped_logs_run_timestamp'), table_name='unmapped_logs')
    op.drop_index(op.f('ix_unmapped_logs_entity_type'), table_name='unmapped_logs')
    op.drop_index(op.f('ix_unmapped_logs_entity_name'), table_name='unmapped_logs')
    op.drop_index('idx_entity_status', table_name='unmapped_logs')
    op.drop_index('idx_entity_name_type', table_name='unmapped_logs')
    op.drop_table('unmapped_logs')
    op.drop_index(op.f('ix_report_runs_timestamp'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_status'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_created_at'), table_name='report_runs')
    op.drop_index('idx_status_created', table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index(op.f('ix_entity_mappings_sales_employee'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_is_active'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_customer_name'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_customer_code'), table_name='entity_mappings')
    op.drop_index('idx_sales_employee_active', table_name='entity_mappings')
    op.drop_index('idx_customer_name_active', table_name='entity_mappings')
    op.drop_index('idx_customer_code_active', table_name='entity_mappings')
    op.drop_table('entity_mappings')
    op.drop_index(op.f('ix_audit_log_user_email'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('idx_user_action', table_name='audit_log')
    op.drop_index('idx_action_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
